### PR TITLE
[python3] Open option ignore_keywords for export operation (since svn 1.7)

### PR DESCRIPTION
**Pull request by ardumont**
Since 1.7, avoiding keyword expansion is a possibility during export.

This opens the call to the new api with that option (false by default).

The test is merely there to ensure the option does not break anything.

api doc: https://subversion.apache.org/docs/api/1.7/group__Export.html#ga012408fea426f8bc283890fdad6f0b1c

Thanks for your time.

Cheers,

### CODE REVIEW

**Comment by ardumont** [comment]
Like i said on irc, python3 branch is not really setuped for travis-ci, that's why it broke.
`On my machine, the test i added works` :d

**Comment by jelmer** [comment]
Cherry-picked, thanks!

**Comment by ardumont** [comment]
@jelmer yeah, that's more logic in that sense.
One thing i don't get though is why do i see so much commits now.
Yesterday, there was only 1 (the one i did...)

Anyway, awesome!

Cheers,

**Comment by jelmer** [comment]
My local python3-branch branch was rebased, which is causing github to see all commits as being different.

**Comment by ardumont** [comment]
Yes, ok!
Thx for the info!

**Pull request closed without merging**
